maximum_availability_zones: 5

engine_version: '5.15.6'

publicly_accessable: false

hostname: amq

logging:
  audit: false
  general: false

# maintenance_window:
#   day: 'Sunday'
#   time: '01:00'
#   timezone: 'Australia/Melbourne'

users:
  - username: administrator
    ssm_path: /amazonmq/administrator
    console_access: true

# amq_config:
#   |
#   <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
#     <broker xmlns="http://activemq.apache.org/schema/core" start="false">
#       <destinationPolicy>
#         <policyMap>
#           <policyEntries>
#             <policyEntry topic=">">
#               <pendingMessageLimitStrategy>
#                 <constantPendingMessageLimitStrategy limit="3000"/>
#               </pendingMessageLimitStrategy>
#             </policyEntry>
#           </policyEntries>
#         </policyMap>
#       </destinationPolicy>
#       <plugins>
#       </plugins>
#     </broker>

ssm_custom_resources:
  custom_policies:
    ssm:
      action:
        - ssm:PutParameter
        - ssm:DeleteParameter
      resource: '*'
  roles:
    SSMCustomResource:
      policies_inline:
        - cloudwatch-logs
        - ssm
  functions:
    SSMSecureParameterCR:
      code: handler.py
      handler: handler.lambda_handler
      runtime: python3.6
      timeout: 15
      role: SSMCustomResource
